/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAccesosRouteImport } from './routes/admin.accesos'
import { Route as AdminActividadRouteImport } from './routes/admin.actividad'
import { Route as AdminClinicasRouteImport } from './routes/admin.clinicas'
import { Route as AdminCuentaRouteImport } from './routes/admin.cuenta'
import { Route as AdminIaRouteImport } from './routes/admin.ia'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminPagosRouteImport } from './routes/admin.pagos'
import { Route as AdminSoporteRouteImport } from './routes/admin.soporte'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccesosRoute = AdminAccesosRouteImport.update({
  id: '/accesos',
  path: '/accesos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActividadRoute = AdminActividadRouteImport.update({
  id: '/actividad',
  path: '/actividad',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClinicasRoute = AdminClinicasRouteImport.update({
  id: '/clinicas',
  path: '/clinicas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCuentaRoute = AdminCuentaRouteImport.update({
  id: '/cuenta',
  path: '/cuenta',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIaRoute = AdminIaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagosRoute = AdminPagosRouteImport.update({
  id: '/pagos',
  path: '/pagos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSoporteRoute = AdminSoporteRouteImport.update({
  id: '/soporte',
  path: '/soporte',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/accesos': typeof AdminAccesosRoute
  '/admin/actividad': typeof AdminActividadRoute
  '/admin/clinicas': typeof AdminClinicasRoute
  '/admin/cuenta': typeof AdminCuentaRoute
  '/admin/ia': typeof AdminIaRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pagos': typeof AdminPagosRoute
  '/admin/soporte': typeof AdminSoporteRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/accesos': typeof AdminAccesosRoute
  '/admin/actividad': typeof AdminActividadRoute
  '/admin/clinicas': typeof AdminClinicasRoute
  '/admin/cuenta': typeof AdminCuentaRoute
  '/admin/ia': typeof AdminIaRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pagos': typeof AdminPagosRoute
  '/admin/soporte': typeof AdminSoporteRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/accesos': typeof AdminAccesosRoute
  '/admin/actividad': typeof AdminActividadRoute
  '/admin/clinicas': typeof AdminClinicasRoute
  '/admin/cuenta': typeof AdminCuentaRoute
  '/admin/ia': typeof AdminIaRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pagos': typeof AdminPagosRoute
  '/admin/soporte': typeof AdminSoporteRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/accesos'
    | '/admin/actividad'
    | '/admin/clinicas'
    | '/admin/cuenta'
    | '/admin/ia'
    | '/admin/login'
    | '/admin/pagos'
    | '/admin/soporte'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/accesos'
    | '/admin/actividad'
    | '/admin/clinicas'
    | '/admin/cuenta'
    | '/admin/ia'
    | '/admin/login'
    | '/admin/pagos'
    | '/admin/soporte'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/accesos'
    | '/admin/actividad'
    | '/admin/clinicas'
    | '/admin/cuenta'
    | '/admin/ia'
    | '/admin/login'
    | '/admin/pagos'
    | '/admin/soporte'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/accesos': {
      id: '/admin/accesos'
      path: '/accesos'
      fullPath: '/admin/accesos'
      preLoaderRoute: typeof AdminAccesosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/actividad': {
      id: '/admin/actividad'
      path: '/actividad'
      fullPath: '/admin/actividad'
      preLoaderRoute: typeof AdminActividadRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clinicas': {
      id: '/admin/clinicas'
      path: '/clinicas'
      fullPath: '/admin/clinicas'
      preLoaderRoute: typeof AdminClinicasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cuenta': {
      id: '/admin/cuenta'
      path: '/cuenta'
      fullPath: '/admin/cuenta'
      preLoaderRoute: typeof AdminCuentaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ia': {
      id: '/admin/ia'
      path: '/ia'
      fullPath: '/admin/ia'
      preLoaderRoute: typeof AdminIaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pagos': {
      id: '/admin/pagos'
      path: '/pagos'
      fullPath: '/admin/pagos'
      preLoaderRoute: typeof AdminPagosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/soporte': {
      id: '/admin/soporte'
      path: '/soporte'
      fullPath: '/admin/soporte'
      preLoaderRoute: typeof AdminSoporteRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAccesosRoute: typeof AdminAccesosRoute
  AdminActividadRoute: typeof AdminActividadRoute
  AdminClinicasRoute: typeof AdminClinicasRoute
  AdminCuentaRoute: typeof AdminCuentaRoute
  AdminIaRoute: typeof AdminIaRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPagosRoute: typeof AdminPagosRoute
  AdminSoporteRoute: typeof AdminSoporteRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccesosRoute: AdminAccesosRoute,
  AdminActividadRoute: AdminActividadRoute,
  AdminClinicasRoute: AdminClinicasRoute,
  AdminCuentaRoute: AdminCuentaRoute,
  AdminIaRoute: AdminIaRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPagosRoute: AdminPagosRoute,
  AdminSoporteRoute: AdminSoporteRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
